### ISSUE TITLE
启动提示[运行环境不符合要求]

### ISSUE THREAD

**Issue by sakuraex** [NoHeart2019/KasR3Hook#1]
![image](https://github.com/user-attachments/assets/4c5fd018-a2b9-400f-9490-95aca3a7388a)
![image](https://github.com/user-attachments/assets/c2607f18-70fd-40b1-a37a-e8a88b279059)

**Comment by NoHeart2019** [comment]
开启测试模式

**Comment by NoHeart2019** [comment]
期待你的反馈
